config/routes.rb
Rails.application.routes.draw do
  # http_verb '/path', to: 'controller#action', as: :prefix
  root to: 'flats#index'
  get '/flats/:id', to: 'flats#show', as: :flat
end

# { id: '12314123'}

# CRUD controller actions
# index -> read all
# show -> read one

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require 'open-uri'

class FlatsController < ApplicationController
  before_action :set_flats, only: [:index, :show]

  # by default, rails shows the view with the same name as the action
  def index
    url = 'https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json'
    json = URI.open(url).read
    @flats = JSON.parse(json)
    # tomorrow:
    # @flats = Flat.all
  end

  def show
    # tomorrow:
    # @flat = Flat.find(id???)
    @flat = @flats.find do |flat|
      flat['id'] == params[:id].to_i
    end
  end

  private

  def set_flats
    url = 'https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json'
    json = URI.open(url).read
    @flats = JSON.parse(json)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container mt-3">
  <h1>Flats</h1>
  <div class="cards">
    <% @flats.each do |flat| %>
      <div class="card-trip">
        <%= image_tag flat['imageUrl'] %>
        <div class="card-trip-infos">
          <div>
            <p><%= flat['name'] %></p>
          </div>
          <h2 class="card-trip-pricing">£<%= flat['price'] %></h2>
        </div>
        <%= link_to '', flat_path(flat['id']), class: 'card-trip-link' %>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container">
  <h1><%= @flat['name'] %></h1>
</div>
<div class="container">
  <%= link_to 'Flats', root_path, class: 'btn btn-light'  %>
  <%= link_to root_path, class: 'btn btn-light' do %>
    <i class="fa-solid fa-house"></i>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StaticAirbnb1105</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>